### ISSUE TITLE
Put the widget (not juste some HTML) of another plugin anywhere

### ISSUE THREAD

**Issue by HTCode** [svivian/q2a-widget-anywhere#3]
This plugin (unlike what its name suggests) allows to put some HTML anywhere. However, it does not allow to put the widget of another plugin anywhere. Is it possible to do that ?

**Comment by svivian** [comment]
Not sure what you mean. If you have another widget plugin then add that and put it where you want.

This plugin is for adding HTML without needing to code an entire plugin yourself.
