### ISSUE TITLE
Share question content instead of homepage

### ISSUE THREAD

**Issue by adrian99420** [svivian/q2a-widget-anywhere#6]
Hi,

Thanks for the awesome plugin. It works very well.

However there is one request, I realized the sharing button always sharing homepage, is there anyway we can change the sharing option to share question content instead of homepage? Thanks!

![image](https://cloud.githubusercontent.com/assets/20685685/20703626/64ce2b1a-b657-11e6-8c5a-7c1bab049ec1.png)

**Comment by svivian** [comment]
I don't think this is anything to do with my plugin. This plugin only shows what you put into it, if sharing is not working it's because of the code you put into it.
