### ISSUE TITLE
Back to plugin options should take to this plugin options only

### ISSUE THREAD

**Issue by gurjyot** [svivian/q2a-widget-anywhere#7]
When I create a widget and try to go back to other widgets, there is just no option. When I click on "Back to plugin options", it takes me to all plugin list instead, it should take me to this plugin options only. Can you do something so that it would take us back to all the widgets only?

**Comment by svivian** [comment]
Yeah it is supposed to go back to the specific plugin options, I think the URL is broken.

**Comment by svivian** [comment]
Now fixed in the latest version.
